apiVersion: v1
kind: Secret
metadata:
  name: mlflow-secret
type: Opaque
data:
  MYSQL_PASSWORD: Predictnow!1
  OCI_BUCKET_URI: p/1q4zS1SxvHEjt36ljCU56W-oeHlNjWRoBTNuIEtAlcYnOFEJqxlSA2Qx_wjlim6D/n/yzdey9wyttei/b/mlflow/o/
